---
title: "Open Data Format: Example"
output:
  github_document:
    toc: true
    toc_depth: 3
---

---
# Example

This data example is intended to illustrate the main features of the specified Open Data Format (ODF). The example was developed along the lines of the [SOEP-Core study from 2010](https://paneldata.org/soep-core/data/bap/), in which, among other instruments, data were collected using the [Individual Questionnaire](https://paneldata.org/soep-core/inst/soep-core-2010-pe/1). Therefore, the metadata of this example is very similar to that of the SOEP survey, but the response data are fictitious. The response data were generated by random selection. The variable `name` is fictional to have an example for character variables. The responses for the variable `name` stem from the dataset "Vornamen 2013" from the Open Data platform [Offene Daten Köln](https://offenedaten-koeln.de/dataset/vornamen).

Since the Open Data Format specifies both, the data component and the metadata component of a dataset, the document is structured in two main sections: [Data](#data) and [Metadata](#metadata).

## Data
The survey response data is saved in the [data.csv](data.csv) file. The dataset contains the seven variables **bap87**, **bap9201**, **bap9001**, **bap9002**, **bap9003**, **bap96** and **name**.

```{r, echo=FALSE, include=TRUE}
data<-read.csv("data.csv")

data[is.na(data)] <- ""

knitr::kable(data,
             caption = 'data.csv holding the raw data'
             )
```

The variables in this example hold different variable types: numeric, character and categorical. Categorical variables are numerical variables with pre-defines labels to values. Solely with the data component of the dataset, categorical variables can not be identified since the value labels are held by the metadata component of the dataset.

<!-- --------------------------------------------------------------------------------- -->
<!-- --------------------------------------------------------------------------------- -->
<!-- --------------------------------------------------------------------------------- -->

## Metadata

For describing the raw data stored in the [data.csv](data.csv) file the [example_dataset.zip](example_dataset.zip) provides a metadata XML file ([metadata.xml](metadata.xml)). The XML file integrates different levels of metadata information using hierarchically nested tags. The `<codebook>` tag includes general information about the metadata schema -- for the Open Data Format the [DDI-Codebook 2.5 schema](https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/field_level_documentation.html) is the basis. For a general description of the dataset, the `<fileDscr>` tag is available. Finally, the `<dataDscr>` tag holds information about the datasets' variables, their missing values, and predefined values and value labels in the case of categorical variables.

### Metadata Schema 

The `<codebook>` tag holds general information about the DDI-Codebook 2.5 schema as attributes. In this area the `version` of the codebook, `xml namespace`, and `schemaLocation` are specified. 

```{xml}
<codeBook 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns="ddi:codebook:2_5" 
  xsi:schemaLocation="ddi:codebook:2_5 http://www.ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd" 
  version="2.5"
  >
```
Code 1: XML code for declaring the metadata schema 

### Study
The `<stdyDscr>`tag includes information about the study where the data was collected.

```{xml}
<stdyDscr>
  <citation>
    <titlStmt>
      <titl>soep-core v38.1</titl>
    </titlStmt>
  </citation>
</stdyDscr>
```

### Dataset
The `<fileDscr>`tag includes information about the dataset by using several sub-tags: The `<fileName>` tag encloses the dataset name, in this case, `bap`. The `<titl>` tag holds the dataset label. In this example, two language versions of the dataset label exist. Therefore, the `<titl>` tag appears twice but with different language declarations. For declaring a language, the XML attribute `xml:lang` comes into play. This attribute holds the language code `"de"` for the German version and `"en"` for the English one. The attribute is mandatory and must be applied even if labels and descriptions are available in only one language.

```{xml}
<fileDscr>
	<fileTxt>
	    <fileName>bap</fileName>
	    <fileCont xml:lang="en">The data were collected as part of the SOEP-Core study using the questionnaire „Living in Germany - Survey 2010 on the social situation - Personal questionnaire“ for all. This questionnaire is addressed to the individual persons in the household. A view of the survey instrument can be found here: https://www.diw.de/documents/dokumentenarchiv/17/diw_01.c.369781.de/soepfrabo_personen_2010.pdf</fileCont>
        <fileCont xml:lang="de">Die Daten wurden im Rahmen der Studie SOEP-Core mittels des Fragebogens „Leben in Deutschland – Befragung 2010 zur sozialen Lage - Personenfragebogen für alle“ erhoben. Dieser Fragebogen richtet sich an die einzelnen Personen im Haushalt. Eine Ansicht des Erhebungsinstrumentes finden Sie hier: https://www.diw.de/documents/dokumentenarchiv/17/diw_01.c.369781.de/soepfrabo_personen_2010.pdf</fileCont>
    	<fileCitation>
    	    <titlStmt>
    	        <titl xml:lang="en">Data from individual questionnaires 2010</titl>
    	      	<titl xml:lang="de">Daten vom Personenfragebogen 2010</titl>
    	    </titlStmt>
        </fileCitation>
    </fileTxt>	 
	<notes>
	    <ExtLink URI="https://paneldata.org/soep-core/data/bap"/>	
    </notes>   
</fileDscr>
```
Code 2: XML code for providing metadata on the dataset level.

For a more specific description of the dataset, such as information about the study or measurement instrument, the `<fileCont>` tag allows an additional space. As with the `<titl>` tag, the `<fileCont>` tag allows for multilingual text descriptions using the `xml:lang` attribute. The `URI` attribute embedded in the `<ExtLink>` tag holds a link to an external platform where additional information for the dataset is available.

### Variables

Code 3 gives an example for describing the variable `bap87` using the ODF specification. All variable metadata is included within the `<dataDscr>` tag, with the metadata for each individual variable contained in a `<var`> tag. The `var` tag allows various sub-tags for describing a variable. For the variable `bap87` from the example, the attribute `name` includes variable name. The `<labl>` tag provides the variable label (e.g., `Current Health`), and the `<txt>` tag a more extensive description of the variable (e.g., `Medical conditions (both physical and mental health)`). Both variable label and variable description have a multilingual support using the `xml:lang` attribute. This example provides the label for the variable `bap87` in English `<labl xml:lang="en">Current Health</labl>` and in German `<labl xml:lang="de">Gegenwärtiger Gesundheitszustand</labl>` by declaring the language with the code `en` and `de`. Similarly, the `<txt>` tag allows for the language specification for variable description. 

```{xml}
	<dataDscr>
		<var name="bap87">
		    <labl xml:lang="en">Current Health</labl>
		    <labl xml:lang="de">Gesundheitszustand gegenwärtig</labl>
		    <txt xml:lang="en">Question: How would you describe your current health?</txt>
		    <txt xml:lang="de">Frage: Wie würden Sie Ihren gegenwärtigen Gesundheitszustand beschreiben?</txt>
  			<catgry>
  	        	<catValu>-2</catValu>
  	        	<labl xml:lang="en">Does not apply</labl>
  	        	<labl xml:lang="de">trifft nicht zu</labl>        	
  	    </catgry>
  	    <catgry>
  	        	<catValu>-1</catValu>
  	        	<labl xml:lang="en">No Answer</labl>
  	        	<labl xml:lang="de">keine Angabe</labl>        	
  	    </catgry>
  	    <catgry>
  	        	<catValu>1</catValu>
  	        	<labl xml:lang="en">Very good</labl>
  	        	<labl xml:lang="de">Sehr gut</labl>        	
  	    </catgry>
  	    <catgry>
  	        	<catValu>2</catValu>
  	        	<labl xml:lang="en">Good</labl>
  	        	<labl xml:lang="de">Gut</labl>        	
  			</catgry>        	
  			<catgry>
  	        	<catValu>3</catValu>
  	        	<labl xml:lang="en">Satisfactory</labl>
  	        	<labl xml:lang="de">Zufriedenstellend</labl>        	        	
  	    </catgry>        	
  	    <catgry>
  	        	<catValu>4</catValu>
  	        	<labl xml:lang="en">Poor</labl>
  	        	<labl xml:lang="de">Weniger gut</labl>        	        	        	
  	    </catgry>        	
  			<catgry>
  	        	<catValu>5</catValu>
  	        	<labl xml:lang="en">Bad</labl>
  	        	<labl xml:lang="de">Schlecht</labl>        	        	
  	    </catgry>	    
  			<varFormat type="numeric"/>
		    <notes>
		    	<ExtLink URI="https://paneldata.org/soep-core/data/bap/bap87"/>
		    </notes> 
	   </var> 
    ... 
  </dataDscr>
```
Code 3: XML code for providing metadata on the variable level.

The `URI` attribute within the `<ExtLink>` tag holds a link to an external website (here, `https://paneldata.org/soep-core/data/bap/bap87`) with detailed information about the variable (e.g. descriptive statistics, methodological or technical reports, documentation of the measurement instrument). The tag `<varFormat` including the attribute `type="numeric"/>` indicates that the data type of variable `bap87` is numeric.

### Variable Values & Value Labels

The `<catgry>` tag subordinates the `<var>` tag and holds the predefined variable values and value labels in the case of categorical variables or user-defined missing values. The `<catValu>` tag includes the variable values, and the `<labl>`tag provides the interpretation of these values. Again, it is possible to use labels in different languages by specifying the `<xml:lang>` attribute with the respective language code (e. g., `"en"`). 

The variable `bap87` from this example holds the values `-2` through `5` assigned to the labels `Does not apply` over `Very good` through `Bad`. The corresponding German version of the value labels is declared with the `xml:lang="de"` attribute.

